baseurl = "https://winstonhoseadriggins.github.io/amirsoulfood/"
languageCode = "en-us"
title = "AMIR`S SOUL FOOD"

[params]
  description = "AMIR`S would like to THANK YOU for your patronage"

[[menu.main]]
    name = "Food"
    url  = "/food"
    weight = 1

[[menu.main]]
    name = "Drinks"
    url  = "/drinks"
    weight = 2

 [[menu.main]]
    name = "About"
    url  = "/about"
    weight = 3