backend:
  name: github
  repo: winstonhoseadriggins/amirsoulfood # Path to your Github repository
  branch: master # Branch to update

media_folder: "src/img/gallery"

collections:
  - name: food
    label: "Food Item"
    folder: "site/content/food"
    create: true
    fields:
      - {label: "Name of Item", name: "title", widget: "string"}
      - {label: "Supported Meals", name: "categories", widget: "list", default: ["lunch","dinner"]}
      - {label: "Ingredients/Description", name: "description", widget: "text"}
      - {label: "Type of Food", name: "type", widget: "string", default: "Seafood"}
      - {label: "Price", name: "price", widget: "string"}
  - name: drinks
    label: "Drink Item"
    folder: "site/content/drinks"
    create: true
    fields:
      - {label: "Name of Drink", name: "title", widget: "string"}
      - {label: "Drink Marker", name: "categories", widget: "hidden", default: ["drinks"]}
      - {label: "Ingredients/Description", name: "description", widget: "text"}
      - {label: "Type of Drinks", name: "type", widget: "string", default: "iced_tea"}
      - {label: "Price", name: "price", widget: "string"}

  - name: gallery
    label: "Gallery Image"
    folder: "site/content/gallery"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Gallery Image", name: "image", widget: "image"}